# Generated by Django 3.0 on 2020-10-06 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=10)),
                ('mi_apellido', models.CharField(max_length=10)),
                ('mi_edad', models.IntegerField(default=0)),
                ('correo_email', models.EmailField(max_length=254)),
                ('celular_telefono', models.IntegerField(default=0)),
                ('mi_ciudad', models.CharField(max_length=20)),
                ('codigo_postal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mi_titulo', models.CharField(max_length=30)),
                ('mi_texto', models.TextField(max_length=1000)),
                ('mi_foto', models.ImageField(upload_to='')),
                ('fecha_publicacion', models.DateTimeField(verbose_name='date published')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylife.Persona')),
            ],
        ),
    ]
