# Generated by Django 3.0 on 2020-10-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0002_auto_20201008_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='mi_foto',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
