# Generated by Django 3.0 on 2020-11-01 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='enviar',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comentario_aprovado',
        ),
    ]
