# Generated by Django 3.0 on 2020-11-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylife', '0005_auto_20201101_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creado',
            new_name='created_date',
        ),
    ]
